# Site settings
title: KyBook Site
email: admin@kybook-reader.com
description: > # this means to ignore newlines until "baseurl:"
  KyBook Ebook Reader for iOS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kybook-reader.com/" # the base hostname & protocol for your site
twitter_username: kybookapp
github_username:  kolyvan

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
